import React from 'react';
import DocumentPage from './DocumentPage';

interface PrivacyPageProps {
  onClose: () => void;
}

const PrivacyPage: React.FC<PrivacyPageProps> = ({ onClose }) => {
  const content = (
    <div className="space-y-6">
      <h1>LinkSnap Privacy Policy – Your Data Stays Yours</h1>
      <p><strong>Last Updated:</strong> March 3, 2026<br/>
      <strong>App:</strong> LinkSnap – AI-Powered Link & Bookmark Manager<br/>
      <strong>Effective For:</strong> All users of LinkSnap web app and PWA</p>

      <h2>Privacy at a Glance</h2>
      <p>LinkSnap is a <strong>zero-tracking, no-account-required</strong> bookmark and link extraction tool. We built LinkSnap on a simple principle: your data belongs to you — not us. No accounts. No servers storing your information. No surveillance. Just a fast, private, and powerful way to manage your links.</p>

      <h2>1. No Account, No Tracking, No Problem</h2>
      <p>LinkSnap is designed to work <strong>without any registration or sign-in</strong>. We do not collect, store, or process any personally identifiable information (PII). That means:</p>
      <ul>
        <li>No name, email address, or phone number is ever requested</li>
        <li>No IP address logging</li>
        <li>No device fingerprinting or device identifiers</li>
        <li>No cookies used for tracking or advertising</li>
        <li>No browsing history recorded</li>
        <li>No location data collected</li>
        <li>No usage analytics or behavioral profiling</li>
      </ul>
      <p>Whether you use LinkSnap once or every day, we have <strong>zero knowledge of who you are</strong>.</p>

      <h2>2. Where Your Data Lives – Entirely on Your Device</h2>
      <p>All data generated by your use of LinkSnap — including bookmarks, extracted links, categories, tags, and preferences — is stored <strong>exclusively in your browser's local storage</strong> (via IndexedDB / localStorage). This data:</p>
      <ul>
        <li>Never leaves your device to LinkSnap servers</li>
        <li>Is fully under your control at all times</li>
        <li>Can be exported, modified, or permanently deleted by you at any time</li>
        <li>Is accessible offline through LinkSnap's Progressive Web App (PWA) mode</li>
      </ul>
      <p><strong>LinkSnap has no access to your saved data. Ever.</strong></p>

      <h2>3. AI-Powered Image Processing – How It Works</h2>
      <p>When you upload a screenshot to extract links, here is exactly what happens:</p>
      <ol>
        <li>Your image is sent <strong>directly from your browser</strong> to the <strong>Google Gemini Vision API</strong> for AI analysis</li>
        <li>The extracted link data is returned directly to your browser</li>
        <li><strong>LinkSnap servers never receive, store, or process your image</strong></li>
      </ol>
      <p>This means the only third party involved in image processing is Google. That processing is governed by <a href="https://policies.google.com/privacy">Google's Privacy Policy</a>. We encourage you to review it.</p>
      <blockquote>
        <p><strong>Your image travels: Your Device → Google Gemini API → Your Device</strong><br/>
        LinkSnap is never in that loop.</p>
      </blockquote>

      <h2>4. Your Gemini API Key – Security & Control</h2>
      <p>To use AI-powered link extraction, you provide your own Google Gemini API key. Here is how LinkSnap handles it:</p>
      <ul>
        <li><strong>Stored locally only</strong> — your API key is saved in your browser's local storage and never transmitted to LinkSnap servers</li>
        <li><strong>Obfuscated before storage</strong> — keys are obfuscated to reduce exposure risk</li>
        <li><strong>You are in full control</strong> — we cannot view, access, or use your API key</li>
      </ul>

      <h3>Best Practices for Your API Key</h3>
      <ul>
        <li>Never share your Gemini API key with anyone</li>
        <li>Rotate your key periodically via the Google Cloud Console</li>
        <li>When switching devices, clear your key from Settings before logging out</li>
      </ul>

      <h2>5. Your Full Data Rights</h2>
      <p>LinkSnap gives you complete, unrestricted control over your data:</p>
      <p><strong>Export</strong> — Download all your saved links and bookmarks as a <strong>neatly organized PDF</strong> or JSON file at any time, with no restrictions. Your exported PDF is cleanly formatted and ready to save, share, or archive.</p>
      <p><strong>Delete</strong> — Clear all data instantly from the Settings panel. Deletion is permanent and unrecoverable — we cannot restore data because we never had it.</p>
      <p><strong>Browser-Level Control</strong> — Clearing your browser cache or using private/incognito mode will remove all LinkSnap data from that session.</p>

      <h2>6. Third-Party Services Used by LinkSnap</h2>

      <h3>Google Gemini API</h3>
      <p>Used solely for AI-powered image analysis and link extraction. Data processing is temporary and subject to <a href="https://policies.google.com/privacy">Google's Privacy Policy</a>. LinkSnap retains no results.</p>

      <h3>Vercel (Hosting Infrastructure)</h3>
      <p>LinkSnap is hosted on Vercel's infrastructure. Vercel may generate standard server-side logs (such as request timestamps and accessed URLs) as part of normal web hosting operations. No personal user data is collected or retained through this process. See <a href="https://vercel.com/legal/privacy-policy">Vercel's Privacy Policy</a> for details.</p>

      <h2>7. Security Measures</h2>
      <p>LinkSnap is built with a client-first security architecture:</p>
      <ul>
        <li>All link extraction and data processing happens <strong>in your browser</strong></li>
        <li>All connections use <strong>HTTPS encryption</strong></li>
        <li><strong>Content Security Policy (CSP) headers</strong> are implemented to prevent unauthorized scripts</li>
        <li>API keys are never exposed in browser console logs</li>
        <li>Invalid or malformed API keys are automatically removed to prevent accidental leaks</li>
      </ul>

      <h2>8. Children's Privacy</h2>
      <p>LinkSnap does not knowingly collect any data from children under the age of 13. Since we collect no personal data from any users, LinkSnap is inherently safe and compliant with children's online privacy standards.</p>

      <h2>9. Changes to This Privacy Policy</h2>
      <p>We may update this Privacy Policy from time to time to reflect changes in our practices or for legal reasons. When we do, the "Last Updated" date at the top of this page will be revised. Your continued use of LinkSnap after any changes constitutes your acceptance of the updated policy.</p>

      <h2>10. Contact Us</h2>
      <p>Have a question, concern, or feedback about LinkSnap's privacy practices? We'd love to hear from you.</p>
      <ul>
        <li><strong>Email:</strong> <a href="mailto:linksnap.ai@gmail.com">linksnap.ai@gmail.com</a></li>
        <li><strong>GitHub Issues:</strong> <a href="https://github.com/sumanthkatta-dev/linksnap">github.com/sumanthkatta-dev/linksnap</a></li>
        <li><strong>Security Details:</strong> See <code>SECURITY.md</code> in the repository for technical documentation</li>
      </ul>

      <p><em>LinkSnap is built for people who value privacy. We don't monetize your data, we don't profile you, and we don't store what isn't ours. That's a promise — not just a policy.</em></p>
    </div>
  );

  return <DocumentPage title="Privacy Policy" content={content} onClose={onClose} />;
};

export default PrivacyPage;
